## 22-07-06

- https://www.youtube.com/watch?v=jOcTX7WaFxk
- 카카오 임진왜란
- 클로바가 최고다

## 선형대수학

- 잘해야 하는건 아니지만 많이 나오니 잘 알아야함
- 벡터에 대해서 명확하게 알아둬야함
- det = 행렬식(determinant)
- 함수를 만들어서 x 값으로 y 값을 예측하는것
- b(바이어스)에 따라서 확대를 시키거나 축소를 시켜야 한다.(방향을 띈다)


### 벡터

- https://www.youtube.com/watch?v=x-Ewz1ukXEA
- 벡터를 배우는 이유 ? 스칼라(크기만 ex/ 온도),  벡터(속도 + 힘 )
- 벡터의 덧셈, 평행사변형의 대각선
- L2와 같다 ( ~~ 릿지 )


#### 다중 공선성(회귀분석) ~~ 종속성(행렬)

- 행렬식이 '0'이 아니면 역행렬이 존재==> 선형독립
- 행렬식이 '0'이면 역행렬이 존재하지 않음 ==> 선형종속
- 이렇게 때문에 역행렬을 봐주는게 좋음

### 역행렬

- 공선성과 결이 같으므로 구해주는게 좋음
- 역행렬을 구할 수 없으면  w, b 구하는게 힘듬
- 꼭 알 필욘 없음

In [6]:
from sklearn.linear_model import LinearRegression
x=np.array([[2,3],[5,6]])
y=np.array([4,5])

model=LinearRegression(fit_intercept=False)
model.fit(x,y)
model.coef_

array([-3.        ,  3.33333333])

In [7]:
##  역행렬을 이용하여서 w값을 계산할수 있음.
x=np.array([[2,3],[5,6]])
y=np.array([4,5])

# 넘파이 역행렬 계산후 곱셈하고 더하기,   # np.linalg.solve(x,y) 로 한번에 가능함
tmp=np.linalg.inv(x)  
print('역행렬\n',tmp)

역행렬
 [[-2.          1.        ]
 [ 1.66666667 -0.66666667]]


In [14]:
### 역행렬은 단위행렬이 존재하는 행렬
## https://thebook.io/080246/part03/ch11/unit23/02/
import sympy as sp

B=np.array([[2,3],[5,6]])
c=np.array([0,0]).reshape(-1,1); c
Bc=np.hstack([B, c]);Bc
sp.Matrix(Bc).rref()    # https://ko.wikipedia.org/wiki/%EC%82%AC%EB%8B%A4%EB%A6%AC%EA%BC%B4%ED%96%89%E

(Matrix([
 [1, 0, 0],
 [0, 1, 0]]),
 (0, 1))

In [9]:
!pip install scipy

In [13]:
!pip install sympy

### 단위행렬

- 일반행렬 x 역행렬 = 단위행렬
- numpy 패키지에서 생성하는 함수가 있음

In [15]:
# 단위행렬 생성
# https://firework-ham.tistory.com/34
print(np.identity(n=3, dtype=np.int8))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 전치행렬

- array 구조는 .T 명령어로 전치행렬 이용가능
- 다양한 방법으로 전치 행렬 이용 가능
  - a.T attribute
  - np.transpose(a) method
  - np.swapaxes(a, 0, 1) method
  
- 전치 행렬을 zip 파일로도 가능.
  - (http://pyengine.blogspot.com/2016/11/python-zip-transpose.html)
  - 전치행렬 = list(zip(*원래 행렬))

In [16]:
### 미션, 전치행렬을 사용하지 않고 numpy의 행열 인덱싱 기능을 이용해서 행과 열을 변경하시오.
## 아래사이트는 추후에 참조하세요.. (넘파이 없이 for로 구현)
## https://hnanmal.tistory.com/entry/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%A0%84%EC%B9%98%ED%96%89%EB%A0%AC-%EC%86%90%EC%88%98-%EB%A7%8C%EB%93%9C%EB%8A%94-%EB%B2%95-%EC%A0%84%EC%B9%98%ED%96%89%EB%A0%AC%ED%95%98%EB%82%98-%EB%A7%8C%EB%93%A4%EC%9E%90%EA%B3%A0-numpy-%EC%84%A4%EC%B9%98%ED%95%98%EC%8B%9C%EB%82%98%EC%9A%94

crim=[20,30,5]
rm=[2,1,0]
x=np.array([crim, rm])

xT=np.zeros((x.shape[1],x.shape[0]), dtype=int)
for col in range(x.shape[0]):
    xT[:,col]=x[col,:]
xT

array([[20,  2],
       [30,  1],
       [ 5,  0]])

In [19]:
d_array = np.array([[2, 5], [1, 3]])      # numpy.array를 사용하여 2x2 행렬 생성

d_array

array([[2, 5],
       [1, 3]])

In [24]:
import numpy as np

crim = [20, 30, 5]
rm = [2, 1, 0]

x = np.array([crim, rm])

print(x)
print(x.T)

[[20 30  5]
 [ 2  1  0]]
[[20  2]
 [30  1]
 [ 5  0]]


In [28]:
tmp = list(zip(*x))
print(tmp)

[(20, 2), (30, 1), (5, 0)]


### 행렬의 내적곱

- wx+b 계산식에 내적곱이 사용됨
- np.bot = 행렬의 곱셈, 곱해지는 부분의 숫자가 같아야만 하기 때문에
- 앞서 배운 전치를 통해서 맞춰줘야 한다.
- dense(unit = 4) 같은 경우
- 못써도 알아야 한다.
- np.dot는 생각보다 쓸일이 많기 때문에 알아야 한다.

In [20]:
import numpy as np

a=[[3,4,5],
   [2,3,4]]
a=np.array(a)
   # 2행3열

b=[[1,2],[5,8],[3,6]]
b=np.array(b)
print(a.shape, b.shape)
np.dot(a,b)   # 행렬의 내적곱

(2, 3) (3, 2)


array([[38, 68],
       [29, 52]])

### 직교행렬(Orthogonal matrix)

- 직교 행렬 표시는 ㅗ이다.
- 선형대수학에서, 직교 행렬(直交行列, orthogonal matrix)은 행벡터와 열벡터가 유클리드 공간의 정규 직교 기저를 이루는 실수 행렬
- 수식적으로는 내적(np.dot)이 0을 뜻함

### 선형독립과 선형종속

- 머신러닝에서 데이터셋 특성(x변수 갯수)이 많아지면 오버피팅(overfitting)이 발생함
- 이러한 현상을 차원의 저주라고 하는데, 이를 해결하는 방법 중 하나로 PCA(Principal Component Analysis)가 있음
- Norm은 벡터의 길이 ( 표기법 : ||  || )
- 역행렬 이용하여 선형독립, 선형종속을 확인할 수 있다.
  - 행렬식 = ad - bc
  - 행렬식이 '0'이 아니면 역행렬이 존재==> 선형독립
  - 행렬식이 '0'이면 역행렬이 존재하지 않음 ==> 선형종속

In [29]:
## 역행렬이 존재하지 않는 선형종속
v1=[4,2]
v2=[8,4]
V=np.array([v1,v2])

import numpy.linalg
print(V)
print(numpy.linalg.det(V)) #  print(4*4-2*8)      # 선형종속,   # 0으로 역행렬이 존재하지 않음.
print('rank % d' % np.linalg.matrix_rank(V)) # 랭크계산, 1이면 선형종속 # https://thebook.io/080246/part03/ch10/unit19/03-18/


print('-'*100)
## 역행렬이 존재하지 않음으로 단위행렬이 존재하지 않음.
B=np.array([v1,v2])
c=np.array([0,0]).reshape(-1,1); c
Bc=np.hstack([B, c]);Bc
sp.Matrix(Bc).rref()

# rank1 이라는것은 같은 차원에 있다. 텐서와 토치에서 간간히 나옴

[[4 2]
 [8 4]]
0.0
rank  1
----------------------------------------------------------------------------------------------------


(Matrix([
 [1, 1/2, 0],
 [0,   0, 0]]),
 (0,))

In [30]:
## 역행렬이 존재하는 선형독립
v1=[3,0]
v2=[0,-2]
V=np.array([v1,v2])
print(V)
print(numpy.linalg.det(V))  # print(3*-2-0*0)   # 0이 아님으로 역행렬 존재
print('rank % d' % np.linalg.matrix_rank(V)) # 랭크계산, 2이상이면 선형독립 # https://thebook.io/080246/part03/ch10/unit19/03-18/

print('-'*100)
## 역행렬이 존재함으로 단위행렬이 생성됨
B=np.array([v1,v2])
c=np.array([0,0]).reshape(-1,1); c
Bc=np.hstack([B, c]);Bc
sp.Matrix(Bc).rref() 

[[ 3  0]
 [ 0 -2]]
-6.0
rank  2
----------------------------------------------------------------------------------------------------


(Matrix([
 [1, 0, 0],
 [0, 1, 0]]),
 (0, 1))

## PCA(Principal Component Analysis, 주성분 분석) 때문에 하는것, 데이터의 벡터값까지 고려해서 새로운 차원을 만드는것

- 추천 시스템 , 행과 열을 분해해서 만드는것 = 차원을 축소

- 가장 기본 작업은 스케일링

- 특성 추출(feature extraction) 방법을 이용

- 데이터에서 주축을 찾고 모든 데이터를 해당 축에 투영시켜서(원본 특성들의 선형 결합으로) 새로운 특성을 만듭니다.

- 편차과 분산의 계산이 0이 나와버리면 계산이 불가함

- 선형성 판단은 공식이나 그림으로 그려볼것

- 여러개의 데이터셋이 나오면 3차원 평면도 나올수 있음

- SVM (서포트 벡터 머신 support vector machine)
  - 데이터 갯수가 작을때는 활용도가 좋다, 아직도 공장이나 분류가 잘 되어있는 데이터에는 사용하기 편함
  - 가장 잘 분류할 수 있는 하나의(Unique) 선형식을 찾으려고 한다.
  - 데이터셋들에게 겹치지 않는 곳에 벡터를 긋는다.
  - 갯수는 지정해줘야 한다.

### 단위벡터

- 고유벡터(unit vector)는 크기가 1이고 방향을 갖는 벡터
- 단위 벡터 만드는것도 하나의 정규화이다. (= 노멀라이즈 스케일러 )
- PCA 하면 스케일링 해서 넣어야 하는데 다시 자동으로 스케일링 하게 되니까 계산이 안맞는다. 그래서 방향성을 체크해서 맞는지 확인해야 한다.
- 데이터간의 위치의 유사도를 보면 되기 때문에, 단위 벡터만 보면 된다.
- 단위벡터 - 방향성만 본다
- 데이터에 정규성을 추가하는 기법

In [31]:
v=[1,-2,3]
print(np.linalg.norm(v,1))  # 1+2+3
print(np.linalg.norm(v,2))   # (1+4+9)**0.5

6.0
3.7416573867739413


In [32]:
import numpy as np

v = np.random.rand(10)
print(v)
print('*'*100)

print('\n▶단위벡터를 출력합니다.\n')
normalized_v = v / np.sqrt(np.sum(v**2))
print(normalized_v)

print('-'*100)

normalized_v = v/np.linalg.norm(v)
print(normalized_v)

print('-'*100)

from sklearn.preprocessing import normalize
normalized_v = normalize(v[:,np.newaxis], axis=0).ravel()
print(normalized_v)

print('-'*100)

from scipy import linalg
v / linalg.norm(v)


# 참고: https://jimmy-ai.tistory.com/81

[0.14750369 0.53644775 0.41531701 0.15305056 0.88586002 0.79986676
 0.24126479 0.88925968 0.49629461 0.13046446]
****************************************************************************************************

▶단위벡터를 출력합니다.

[0.08456716 0.30755747 0.23811051 0.0877473  0.50788332 0.45858147
 0.13832249 0.50983242 0.28453678 0.07479819]
----------------------------------------------------------------------------------------------------
[0.08456716 0.30755747 0.23811051 0.0877473  0.50788332 0.45858147
 0.13832249 0.50983242 0.28453678 0.07479819]
----------------------------------------------------------------------------------------------------
[0.08456716 0.30755747 0.23811051 0.0877473  0.50788332 0.45858147
 0.13832249 0.50983242 0.28453678 0.07479819]
----------------------------------------------------------------------------------------------------


array([0.08456716, 0.30755747, 0.23811051, 0.0877473 , 0.50788332,
       0.45858147, 0.13832249, 0.50983242, 0.28453678, 0.07479819])

### 직교벡터

- 두 벡터 사이의 각도가 90도
- ||a||2 + ||b||2 = ||a + b||2
- 직교 행렬 인지 확인하는 방법은? 공식 사용, 내적곱 = 0 이면 직교 행렬


- 벡터 커리 구하는법 : 유클리드 거리, 맨해튼 거리, 코사인 거리 => 추천 시스템 및 문서의 유사도를 구하는 데 사용

In [33]:
### 아래 두 자료는 직교 행렬임
# https://thebook.io/080246/part03/ch10/unit20/03-03/
def orthogonal(v1,v2):
    return (np.sum(v1**2+v2**2))**0.5 == (np.sum((v1+v2)**2))**0.5

a=np.array([0,-1,0])
b=np.array([1,0,0])
c=np.array([0,0,1])
d=np.array([0,1,1])

print(orthogonal(a,b),orthogonal(a,c),orthogonal(b,c),orthogonal(c,d))
print(np.dot(a,b),np.dot(a,c),np.dot(b,c),np.dot(c,d))


## 
# np.sum(x.T*x+y.T*y)==np.sum((x+y).T*(x+y))
# np.dot(x.T,x)+np.dot(y.T,y) == np.dot((x+y).T, (x+y))

True True True False
0 0 0 1


In [34]:
# 코사인각도값을 이용하여서 직교행렬 여부 확인하기
# 코사인각도값이 0 이나오면 직교행렬임 (두 벡터가 이루는 각이 작을수록 유사도가 높고, 각이 클수록 유사도가 낮습니다.)
from numpy.linalg import norm
def cos_sim(A, B):
    return np.dot(A, B)/(norm(A)*norm(B))     # norm 옵션없으면 기본값 norm2임 (제곱값의합**0.5)
cos_sim(a,b),cos_sim(a,c),cos_sim(b,c),cos_sim(c,d)

(0.0, 0.0, 0.0, 0.7071067811865475)

In [36]:
v=[1,-2,3]
norm(v,2)

3.7416573867739413

In [35]:
x=np.array([2,1,3])
y=np.array([3,3,-3])
orthogonal(x,y)

True

### thebook 3-20 까지 정리


- wordcloud 는 빈도수 세는거에서만 추천
- LDA = 토픽으로 유사도가 높은 단어들을 모음
- text 쪽은 완전 별개로 강의를 해주실것이다.


In [37]:
# NumPy 라이브러리를 호출하고 코사인 공식을 적용하려고
# 내적(dot)과 벡터의 크기(norm)를 호출합니다
# 또 공식을 적용할 수 있는 함수(def cos_sim())를 생성합니다
from numpy import dot
from numpy.linalg import norm
import numpy as np

def cos_sim(A, B):
    return dot(A, B)/(norm(A)*norm(B))

# 표 10-10의 행렬을 배열로 저장합니다
doc1 = np.array([1, 1, 1, 1, 0])
doc2 = np.array([1, 0, 1, 0, 1])
doc3 = np.array([2, 1, 1, 1, 1])

# 코사인 함수에 배열 값을 적용한 후 유사도 정도를 출력합니다
print(cos_sim(doc1, doc2)) # 문서 1과 문서 2의 코사인 유사도
print(cos_sim(doc1, doc3)) # 문서 1과 문서 3의 코사인 유사도
print(cos_sim(doc2, doc3)) # 문서 2와 문서 3의 코사인 유사도

0.5773502691896258
0.8838834764831843
0.8164965809277259


### 차원축소법

- PCA(Principal component를 활용): 차원을 줄이면서 정보의 손실을 최소화함
- 직교 행렬의 행렬값 분해
- svd 특이값분해(Singular Value Decomposition, SVD) 가 속도가 빠름. -> PCA를 진행하기도 함.
- 고유값 구하기, 고유값의합은 분산의 합과 같음


- 위와 같은것들은 주성분분석이라고함
- PCA 쪽이 시각화가 많이 떨어짐
- 데이터셋 잡을때 잘 맞음
- 분석 도구 다른것으로 돌려볼려면 돌려볼것



#### 고유벡터


- 자료의 방향성이 같은 벡터
- 라면 자료 ( https://studychfhd.tistory.com/228 )
- 스케일러를 꼭 해줘야 한다.
- 트렌스폼, 라면의 데이터 셋만 가져간다.
- PCA에 fit 해주면 된다.
- array값 해석이 쉽지 않다.
- pca 가 여러게 나와도 설명력에 대해서 고민하고 그려야 한다.
- 빅데이터에서는 추천하지 않음
- 테스트 마이닝도 PCA로 함
- 설명력이 떨어져도 PCA를 많이 안하는걸 권장,
- 고전적 데이터 는 PCA가 가능하다. 

## 현재 까지 비지도 학습

- 우선 데이터를 벡터 형식으로 뿌린다.
- 응집점을 만든다.
- kmeans = 3 , 중심점을 3개 뿌린다. y 값이 없는 분류 분석 기법
  - 백터들을 모은 후 백터들의 평균값으로 이동함, <= 반복
  - 분류하는 중심접 데이터가 계속 바뀐다. 비슷한 벡터들 끼지 모아내는것
  - k는 숫자다.
  - 이러한 분석을 군집 분석 ( 쇼핑몰 비슷한 구매 패턴끼리 모아주세요 )
  
- kNN은 대표적인 지도학습(거의 안씀), k 의 갯수만큼 모으기

- 현재는 xgboost, 랜덤포레스트, L1, L2 쓰고 정확도가 80정도만 나와도 된다.

## dacon

- 쇼핑몰 지점별 매출액 예측 경진대회가 분석이 어려운 이유는
  - 계절성이 띄고 있는 자료는 분석이 어렵다, 시계열 분석이 따로 있지만 데이터가 작을때 얘기다.
  - 달을 나눠서 다시 만들어주는 시계열 데이터, 선형성(뻗어나감)을 제거해서 해줘야 한다.
  - 쇼핑몰의 분류나 평일/주말 분류나 지역에 따른 분류에 따라 다르기 때문에 분석하기 힘들다.
  - 국내 자료는 계절성을 띄다보니 

## 데이터프레임 Groupby에 대한 강의

- 