# ▶Part1. 토큰화
- 문장에서 토큰으로 나눌 구분자를 이용하여 단어 분리

->결과 [['파이썬', '차트', '파이썬', '머신러닝'], ['차트', '파이썬', 'R', '차트'], ['R', '분석', '시각화']]



In [2]:
# 코드의 편의성을 위해서 txt자료는 빈칸단위로 분리할수 있는 자료준비
import numpy as np
txt=['파이썬 차트 파이썬 머신러닝',
      '차트 파이썬 R 차트',
       'R 분석 시각화'
      ]

#외부데이터 불러오기
f=open('샘플텍스트.txt','r',encoding='utf-8')
tmp=f.read()
tmp=tmp[1:len(tmp)-1]
txt=tmp.split('\n')
txt



  




['파이썬 차트 파이썬 머신러닝', '차트 파이썬 R 차트', 'R 분석 시각화']

In [3]:
############################ 
##  [방법1] 빈칸단위로 나누기
###############################
txtList=[]
for i in txt:
  txtList.append(i.split(' '))
txtList

[['파이썬', '차트', '파이썬', '머신러닝'], ['차트', '파이썬', 'R', '차트'], ['R', '분석', '시각화']]

In [4]:
############################ 
##  [방법2] 데이터 나누기 컴프리헨션
###############################

txtList=[i.split(' ') for i in txt]
txtList


[['파이썬', '차트', '파이썬', '머신러닝'], ['차트', '파이썬', 'R', '차트'], ['R', '분석', '시각화']]

# ▶Part2. 토큰 데이터 셋 1차원으로 변형
- 중복단어를 제거하여 고유값으로 필드를 제작하기 전 1차원 리스트로 변경해야함.

In [5]:
############################ 
##  [방법1]  2차원리스트를 1차원으로 변형
###############################
import numpy as np

dataList=[]

for i in txtList:
  for j in i:
    dataList.append(j)


dataList

['파이썬', '차트', '파이썬', '머신러닝', '차트', '파이썬', 'R', '차트', 'R', '분석', '시각화']

In [6]:
############################ 
##  [방법2] 2차원 리스트 1차원 결합 컴프리헨션
###############################

dataList=[j for i in txtList for j in i]
dataList


['파이썬', '차트', '파이썬', '머신러닝', '차트', '파이썬', 'R', '차트', 'R', '분석', '시각화']

In [7]:
############################ 
##  [방법3] 넘파이를 이용하여서 한개의 리스트로 제작가능
###############################
dataList=np.concatenate(np.array(txtList))
dataList

C:\Users\BSS\AppData\Local\Temp\ipykernel_21016\3782268571.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  dataList=np.concatenate(np.array(txtList))


array(['파이썬', '차트', '파이썬', '머신러닝', '차트', '파이썬', 'R', '차트', 'R', '분석',
       '시각화'], dtype='<U4')

# ▶Part3. 단어필드제작- 단어 unique
- 중복단어를 제거하여 고유값으로 필드를 제작
- 결과-> ['R', '머신러닝', '분석', '시각화', '차트', '파이썬']

In [10]:
############################ 
##  [방법1] 중복제거, 이 작업은 중복제거 되지만 sort는 되지 않음.
###############################

uniqueList=[]
for i in dataList:
  if i not in uniqueList:
      uniqueList.append(i)

uniqueList=sorted(uniqueList)
uniqueList

['R', '머신러닝', '분석', '시각화', '차트', '파이썬']

In [9]:
############################ #####################
##  [방법2]  넘파이 제공 unique함수 사용
##  이 unique함수에 대한 기술은 아래 사이트에서 확인하면 됨
##  ##  https://github.com/numpy/numpy/blob/v1.21.0/numpy/lib/arraysetops.py#L138-L317
##  위의 사이트에서 unique 함수에 대하여 확인
####################################################

np.unique(tmp)


array(['파이썬 차트 파이썬 머신러닝\n차트 파이썬 R 차트\nR 분석 시각화'], dtype='<U36')

In [183]:
############################ #####################
##  [방법3]  set함수를 이용
## set함수는 index를 제공하지 않음. list함수로 변경해야함
####################################################

a=list(set(dataList))
a[0]


'파이썬'

# ▶Part4. 단어별 Count(빈도수 제작)

In [226]:
#######################################
### DTM 제작, count함수 사용
### [방법1] count함수 사용
######################################
import pandas as pd
dtm=[]
for a in uniqueList:
  row=[]
  for i in txtList:
    row.append(i.count(a))
  dtm.append(row)
df=pd.DataFrame(dtm)
df=df.T
df.columns=uniqueList
df

numdf=df.values
print(np.sum(numdf,axis=0))
print(np.sum(numdf,axis=1))

df

[3 3 1 2 1 1]
[4 4 3]


파이썬  차트  머신러닝  R  분석  시각화
0    2   1     1  0   0    0
1    1   2     0  1   0    0
2    0   0     0  1   1    1

In [36]:
######################################
### 컬럼자료의 출현횟수를 계산함.
### 직접작성
### [방법2] count함수도 직접 제작
###################################
import pandas as pd
result=[]

for col in uniqueList:   # 리스트의처음값 'R'로 보기
    list_=[]
    for row in txtList:      #1번행에서 확인
        cnt=0
        
        for item in row:
            if col==item:
                cnt=cnt+1
        # print('------------------------------')
        #print('검색단어: %s   검색된횟수: %d' %(col,cnt))
        
        list_.append(cnt)
    result.append(list_)

df = pd.DataFrame(result)
print(df)

print('--------------------------')
df=df.T
print(df)


df.columns = uniqueList
display(df)

print(np.sum(df.values, axis=1))
print(np.sum(df.values, axis=0))

   0  1  2
0  0  1  1
1  1  0  0
2  0  0  1
3  0  0  1
4  1  2  0
5  2  1  0
--------------------------
   0  1  2  3  4  5
0  0  1  0  0  1  2
1  1  0  0  0  2  1
2  1  0  1  1  0  0


R  머신러닝  분석  시각화  차트  파이썬
0  0     1   0    0   1    2
1  1     0   0    0   2    1
2  1     0   1    1   0    0

[4 4 3]
[2 1 1 1 3 3]


In [ ]:
#######################################################
####### 방법3
#######################################################
txt=['파이썬 차트 파이썬 머신러닝',
      '차트 파이썬 R 차트',
       'R 분석 시각화'
      ]

vocab = list(set(w for doc in  txt for w in doc.split()))
vocab.sort()
vocab


def tf(t, d):
    return d.count(t)

result = []
N=len(txt)
for i in range(N): # 각 문서에 대해서 아래 명령을 수행
    result.append([])
    d = txt[i]
    for j in range(len(vocab)):
        t = vocab[j]        
        result[-1].append(tf(t, d))

tf_ = pd.DataFrame(result, columns = vocab)
tf_

R  머신러닝  분석  시각화  차트  파이썬
0  0     1   0    0   1    2
1  1     0   0    0   2    1
2  1     0   1    1   0    0

In [234]:
######################################################
#### 참고: 사이킷런 제공모듈
#####################################################3
txt=['파이썬 차트 파이썬 머신러닝',
      '차트 파이썬 R 차트',
       'R 분석 시각화'
      ]


from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer() # 일반적으로 공백을 기준으로 나눔
tdm = cv.fit_transform(txt)

display(tf_)
print(tdm)


# 단어목록 확인
feature=cv.get_feature_names()
print(feature)

print('\n-----tf Matrix------')
txtTDM=tdm.todense()
print(txtTDM)


pd.DataFrame(tdm.todense(), columns=feature)

R  머신러닝  분석  시각화  차트  파이썬
0  0     1   0    0   1    2
1  1     0   0    0   2    1
2  1     0   1    1   0    0

  (0, 4)	2
  (0, 3)	1
  (0, 0)	1
  (1, 4)	1
  (1, 3)	2
  (2, 1)	1
  (2, 2)	1
['머신러닝', '분석', '시각화', '차트', '파이썬']

-----tf Matrix------
[[1 0 0 1 2]
 [0 0 0 2 1]
 [0 1 1 0 0]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


머신러닝  분석  시각화  차트  파이썬
0     1   0    0   1    2
1     0   0    0   2    1
2     0   1    1   0    0

In [38]:
########################################################
##### 참고: 장바구니 분석을 위한 count
#########################################################

txt=['파이썬 차트 파이썬 머신러닝',
      '차트 파이썬 R 차트',
       'R 분석 시각화'
      ]
vocab = list(set(w for doc in  txt for w in doc.split()))

result=[]
for data in txtList:
    
    list_=[1   if x in data  else 0  for x in uniqueList]
    result.append(list_)
result 

pd.DataFrame(result,columns=uniqueList)

R  머신러닝  분석  시각화  차트  파이썬
0  0     1   0    0   1    1
1  1     0   0    0   1    1
2  1     0   1    1   0    0

# ▶Part4. TF-IDF제작-1

In [235]:
########################################################
##### Part4의 방법2임
#########################################################

txt=['파이썬 차트 파이썬 머신러닝',
      '차트 파이썬 R 차트',
       'R 분석 시각화'
      ]

vocab = list(set(w for doc in  txt for w in doc.split()))
vocab.sort()
vocab


def tf(t, d):
    return d.count(t)

result = []
N=len(txt)

for i in txt: 
 
  result.append([])
  for j in vocab:
        result[-1].append(tf(j, i))
    
tf_ = pd.DataFrame(result, columns = vocab)
tf_


R  머신러닝  분석  시각화  차트  파이썬
0  0     1   0    0   1    2
1  1     0   0    0   2    1
2  1     0   1    1   0    0

In [237]:
from math import log # IDF 계산을 위해

In [238]:
N=len(tf_)
print(N)
re=[]

for row in tf_.values:
  line=[]
 
  for col in row:
    line.append(log(N/(col+1)))
  re.append(line)
pd.DataFrame(np.array(result)*np.array(re),columns=vocab)



3


R      머신러닝        분석       시각화        차트       파이썬
0  0.000000  0.405465  0.000000  0.000000  0.405465  0.000000
1  0.405465  0.000000  0.000000  0.000000  0.000000  0.405465
2  0.405465  0.000000  0.405465  0.405465  0.000000  0.000000

# ▶ Part5. TF-IDF제작-2
 - https://wikidocs.net/31698

In [42]:
def tf(t, d):
    return d.count(t)

def idf(t):
    
    df = 0
    for doc in docs:
        df += t in doc
    return log(N/(df + 1))

def tfidf(t, d):
  return tf(t,d)* idf(t)


def split(docs):
  return list(set(w for doc in docs for w in doc.split()))


In [48]:
###############################################################
### TF-IDF제작
################################################################

import pandas as pd # 데이터프레임 사용을 위해
from math import log # IDF 계산을 위해

docs = [
  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
] 
vocab = split(docs)
vocab.sort()


N=len(docs)

result = []
for i in range(N):
  result.append([])
  d = docs[i]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tfidf(t,d))

tfidf_ = pd.DataFrame(result, columns = vocab)
tfidf_

과일이        길고        노란        먹고       바나나        사과        싶은  \
0  0.000000  0.000000  0.000000  0.287682  0.000000  0.693147  0.287682   
1  0.000000  0.000000  0.000000  0.287682  0.287682  0.000000  0.287682   
2  0.000000  0.693147  0.693147  0.000000  0.575364  0.000000  0.000000   
3  0.693147  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         저는       좋아요  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.693147  0.693147

In [2]:
%cd /content/drive/MyDrive/rapa/on-line
!ls



/content/drive/MyDrive/rapa/on-line
 부성순_동영상1,2			 '텍스트빈도수분석 .ipynb'
 Call_911.ipynb				  텍스트연관성분석.ipynb
 data					  MyTf.py
'동영상강의에 사용된 자료 drinks.ipynb'   Nltk.ipynb
'연관분석(장바구니분석).ipynb'		  __pycache__


In [50]:
import MyTf as mytf

import pandas as pd # 데이터프레임 사용을 위해


docs = [
  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
] 
vocab = mytf.split(docs)                  # MyTf.py 모듈 사용
vocab.sort()

N=len(docs)

result = []
for i in range(N):
  result.append([])
  d = docs[i]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(mytf.tfidf(t,d,docs))    # MyTf.py 모듈 사용
    

tfidf_ = pd.DataFrame(result, columns = vocab)
tfidf_



과일이        길고        노란        먹고       바나나        사과        싶은  \
0  0.000000  0.000000  0.000000  0.287682  0.000000  0.693147  0.287682   
1  0.000000  0.000000  0.000000  0.287682  0.287682  0.000000  0.287682   
2  0.000000  0.693147  0.693147  0.000000  0.575364  0.000000  0.000000   
3  0.693147  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         저는       좋아요  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.693147  0.693147

In [46]:
###############################################################
### 사이킷런 모듈 TF-IDF 
################################################################

from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [

  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
   
]

tfidfv = TfidfVectorizer().fit(corpus)

# 열이름 가져오기
features=tfidfv.get_feature_names()
print('\n▶열이름 출력'+'='*100)
print(features)


######################################################################################
### 사이킷런에서 제공하는 TF-IDF
###
### TF-IDF 계산
#####################################################################################
# 일반 배열 구조로 변환함.
# 이 변환자료와 위의 단어자료를 합쳐서 데이터 프레임으로 작업하면됨
print('\n▶TF-IDF 계산행렬'+'='*100)
print(tfidfv.transform(corpus).toarray())

## 
print('\n▶'+'='*100)

tmp=tfidfv.transform(corpus).toarray()
import pandas as pd
# display(pd.DataFrame(tmp,columns=features))
display(pd.DataFrame(tmp,columns=features))



▶열이름 출력====================================================================================================
['과일이', '길고', '노란', '먹고', '바나나', '사과', '싶은', '저는', '좋아요']

▶TF-IDF 계산행렬====================================================================================================
[[0.         0.         0.         0.52640543 0.         0.66767854
  0.52640543 0.         0.        ]
 [0.         0.         0.         0.57735027 0.57735027 0.
  0.57735027 0.         0.        ]
 [0.         0.47212003 0.47212003 0.         0.7444497  0.
  0.         0.         0.        ]
 [0.57735027 0.         0.         0.         0.         0.
  0.         0.57735027 0.57735027]]

▶====================================================================================================


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


과일이       길고       노란        먹고      바나나        사과        싶은       저는  \
0  0.00000  0.00000  0.00000  0.526405  0.00000  0.667679  0.526405  0.00000   
1  0.00000  0.00000  0.00000  0.577350  0.57735  0.000000  0.577350  0.00000   
2  0.00000  0.47212  0.47212  0.000000  0.74445  0.000000  0.000000  0.00000   
3  0.57735  0.00000  0.00000  0.000000  0.00000  0.000000  0.000000  0.57735   

       좋아요  
0  0.00000  
1  0.00000  
2  0.00000  
3  0.57735

In [45]:
############################################################################################
### TF-IDF 참고 
### analyzer 학습단위를 결정하는 파라미터
### analyzer = 'word'라고 설정시, 학습의 단위를 단어로 설정합니다. 
### (ex - home, go, my ...) analyzer = 'char'라고 설정시, 학습의 단위를 글자로 설정합니다.(ex - a, b, c, d ...)

### 단어: 단어를 오름차순으로 했을때의 순서번호
### 딥러닝에서도 단어분석시에 다음과 같이 딕셔너리의 형식으로 단어와 인덱스 번호를 갖게 됩니다.
### 인덱스 번호는 사용하는 패키지에 따라 방법으로 부여함. (오름차순 또는 출현횟수순등.)
#########################################################################################

vectorizer = TfidfVectorizer(analyzer = 'word')
vectorizer.fit(corpus)
print(sorted(vectorizer.vocabulary_.items()))

print('\n-----------------------------------------------------------')
print(vectorizer.transform(corpus))




[('과일이', 0), ('길고', 1), ('노란', 2), ('먹고', 3), ('바나나', 4), ('사과', 5), ('싶은', 6), ('저는', 7), ('좋아요', 8)]


In [97]:
#####################################################
# 확률적 경사하강법을 이용한 문장 유사도 구하기
######################################################

from sklearn.linear_model import SGDClassifier
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [

  '전화 문의 불편 빠른 응답 전화 친절',
  '안내 불편 전화 무응답 전화 안내 불편',
  '배달비 비쌈 배달 느림 배달 불친절 안내 불편',
  '배달 용기 변경 요망 배달 속도 개선'
   
]

answer=[
        '전화관련과 안내관련 업무에 대해 다시한번 살펴보고 조치하겠습니다',
        '안내시스템 관련 부서로 연결하겠습니다.',
        '배달과 관련한 불편사항을 자세하게 말씀해주세요',
        '배달관련 부서에 전달하겠습니다'
]
       
tfidfv = TfidfVectorizer().fit(corpus)

X=tfidfv.fit_transform(corpus)
y=[1,2,3,4]

model=SGDClassifier(loss='perceptron')
model.fit(X,y)

newX=tfidfv.transform(['전화 연결 안됢'])
pred=model.predict(newX)
pred[0]
answer[pred[0]]

'안내시스템 관련 부서로 연결하겠습니다.'